
name: Manual PyPI Release

on:
  workflow_dispatch:
    inputs:
      pypi_token:
        description: 'PyPI API Token'
        required: true
        type: string

jobs:
  bump-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Bump version
        id: bump_version
        run: |
          new_version=$(python scripts/bump_version.py)
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pyproject.toml
          git commit -m "chore: Bump version to ${{ steps.bump_version.outputs.new_version }}"
          git tag "v${{ steps.bump_version.outputs.new_version }}"
          git push
          git push --tags

      - name: Build and publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ github.event.inputs.pypi_token }}
