
name: Manual PyPI Release

on:
   workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.0.0)'
        required: true
        type: string

jobs:
 bump-version-and-release:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
         token: ${{ secrets.GH_TOKEN }}

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'

     

     

     - name: Build and publish to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         password: ${{ secrets.PYPI_API_TOKEN }}