
name: Publish Python distribution to PyPI

on:
  push:
    tags:
      # Use glob patterns (not regex). This matches vMAJOR.MINOR.PATCH and pre-releases.
      - 'v*.*.*'

jobs:
  build-and-publish:
   name: Build and publish Python distribution to PyPI
   runs-on: ubuntu-latest
   # Required for GitHub OIDC trusted publishing
   permissions:
     id-token: write
     contents: read
   environment: pypi
   steps:
     - uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.x"

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install build

     - name: Build package
       run: python -m build

     - name: Skip publish in local act runs
       if: ${{ env.ACT }}
       run: echo "ACT detected; skipping real PyPI publish."

     - name: Publish package to PyPI (Trusted Publishing)
       if: ${{ !env.ACT }}
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         print-hash: true
