
name: Publish Python distribution to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    # OIDC (Trusted Publishing) intentionally disabled for now.
    # permissions:
    #   id-token: write
    #   contents: read
    # No environment gating to ensure fully automatic publish
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      # Token-based publish (use repo secret PYPI_API_TOKEN). OIDC is commented out above.
      - name: Publish package to PyPI (API token)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print-hash: true
