
name: Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow creating tags/releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for releaser-pleaser to analyze commit history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Or your preferred Python version

      - name: Run Releaser Pleaser
        id: releaser
        uses: apricote/releaser-pleaser@v0.7.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main

      # Keep it simple: rely entirely on releaser-pleaser to create the
      # version bump, tag, and GitHub Release. No fallback logic here.
